In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import csv
import json

In [2]:
data = "data_copy/final_df.csv"

df = pd.read_csv(data)
df.head(20)

,Unnamed: 0,Name,Alignment,Intelligence_x,Strength,Speed,Durability_x,Power,Combat,Total,...,Web Creation,Reality Warping,Odin Force,Symbiote Costume,Speed Force,Phoenix Force,Molecular Dissipation,Vision - Cryo,Omnipresent,Omniscient
0,0,A-Bomb,good,38,100,17,80,17,64,316,...,False,False,False,False,False,False,False,False,False,False
1,1,Abe Sapien,good,88,14,35,42,35,85,299,...,False,False,False,False,False,False,False,False,False,False
2,2,Abin Sur,good,50,90,53,64,84,65,406,...,False,False,False,False,False,False,False,False,False,False
3,3,Abomination,bad,63,80,53,90,55,95,436,...,False,False,False,False,False,False,False,False,False,False
4,4,Abraxas,bad,88,100,83,99,100,56,526,...,False,False,False,False,False,False,False,False,False,False
5,5,Adam Monroe,good,63,10,12,100,71,64,320,...,False,False,False,False,False,False,False,False,False,False
6,6,Adam Strange,good,1,1,1,1,0,1,5,...,False,False,False,False,False,False,False,False,False,False
7,7,Agent Bob,good,10,8,13,5,5,20,61,...,False,False,False,False,False,False,False,False,False,False
8,8,Agent Zero,good,75,28,38,80,72,95,388,...,False,False,False,False,False,False,False,False,False,False
9,9,Air-Walker,bad,50,85,100,85,100,40,460,...,False,False,False,False,False,False,False,False,False,False
10,10,Alan Scott,good,63,80,23,90,98,32,386,...,False,False,False,False,False,False,False,False,False,False
11,11,Alex Woolsly,good,1,1,1,1,0,1,5,...,False,False,False,False,False,False,False,False,False,False
12,12,Allan Quatermain,good,1,1,1,1,0,1,5,...,False,False,False,False,False,False,False,False,False,False
13,13,Amazo,bad,75,100,100,100,100,100,575,...,False,False,False,False,False,False,False,False,False,False
14,14,Ammo,bad,1,1,1,1,0,1,5,...,False,False,False,False,False,False,False,False,False,False
15,15,Ando Masahashi,good,1,1,1,1,0,1,5,...,False,False,False,False,False,False,False,False,False,False
16,16,Angel,good,63,13,46,64,17,42,245,...,False,False,False,False,False,False,False,False,False,False
17,17,Angel,good,63,13,46,64,17,42,245,...,False,False,False,False,False,False,False,False,False,False
18,18,Angel Salvadore,good,38,10,28,28,46,60,210,...,False,False,False,False,False,False,False,False,False,False
19,19,Angela,bad,1,1,1,1,0,1,5,...,False,False,False,False,False,False,False,False,False,False

In [3]:
df.drop(['Unnamed: 0'], axis=1, inplace=True)
df.head()

,Name,Alignment,Intelligence_x,Strength,Speed,Durability_x,Power,Combat,Total,Gender,...,Web Creation,Reality Warping,Odin Force,Symbiote Costume,Speed Force,Phoenix Force,Molecular Dissipation,Vision - Cryo,Omnipresent,Omniscient
0,A-Bomb,good,38,100,17,80,17,64,316,Male,...,False,False,False,False,False,False,False,False,False,False
1,Abe Sapien,good,88,14,35,42,35,85,299,Male,...,False,False,False,False,False,False,False,False,False,False
2,Abin Sur,good,50,90,53,64,84,65,406,Male,...,False,False,False,False,False,False,False,False,False,False
3,Abomination,bad,63,80,53,90,55,95,436,Male,...,False,False,False,False,False,False,False,False,False,False
4,Abraxas,bad,88,100,83,99,100,56,526,Male,...,False,False,False,False,False,False,False,False,False,False

In [4]:
columns = df.columns
for c in columns:
    print (c)

Name
Alignment
Intelligence_x
Strength
Speed
Durability_x
Power
Combat
Total
Gender
EyeColor
Race
HairColor
Publisher
SkinColor
Height
Weight
Agility
Accelerated Healing
Lantern Power Ring
Dimensional Awareness
Cold Resistance
Stealth
Energy Absorption
Flight
Danger Sense
Underwater breathing
Marksmanship
Weapons Master
Power Augmentation
Animal Attributes
Longevity
Super Strength
Cryokinesis
Telepathy
Energy Armor
Energy Blasts
Duplication
Size Changing
Density Control
Stamina
Astral Travel
Audio Control
Dexterity
Omnitrix
Super Speed
Possession
Animal Oriented Powers
Weapon-based Powers
Electrokinesis
Darkforce Manipulation
Death Touch
Teleportation
Enhanced Senses
Telekinesis
Energy Beams
Magic
Hyperkinesis
Jump
Clairvoyance
Dimensional Travel
Power Sense
Shapeshifting
Peak Human Condition
Immortality
Camouflage
Element Control
Phasing
Astral Projection
Electrical Transport
Fire Control
Projection
Summoning
Enhanced Memory
Reflexes
Invulnerability
Energy Constructs
Force Fields
Self-Sustenance
Anti-Gravity
Empathy
Power Nullifier
Radiation Control
Psionic Powers
Elasticity
Substance Secretion
Elemental Transmogrification
Technopath/Cyberpath
Photographic Reflexes
Seismic Power
Animation
Precognition
Mind Control
Fire Resistance
Power Absorption
Enhanced Hearing
Nova Force
Insanity
Hypnokinesis
Animal Control
Natural Armor
Intangibility
Enhanced Sight
Molecular Manipulation
Heat Generation
Adaptation
Gliding
Power Suit
Mind Blast
Probability Manipulation
Gravity Control
Regeneration
Light Control
Echolocation
Levitation
Toxin and Disease Control
Banish
Energy Manipulation
Heat Resistance
Natural Weapons
Time Travel
Enhanced Smell
Illusions
Thirstokinesis
Hair Manipulation
Illumination
Omnipotent
Cloaking
Changing Armor
Power Cosmic
Biokinesis
Water Control
Radiation Immunity
Vision - Telescopic
Toxin and Disease Resistance
Spatial Awareness
Energy Resistance
Telepathy Resistance
Molecular Combustion
Omnilingualism
Portal Creation
Magnetism
Mind Control Resistance
Plant Control
Sonar
Sonic Scream
Time Manipulation
Enhanced Touch
Magic Resistance
Invisibility
Sub-Mariner
Radiation Absorption
Intuitive aptitude
Vision - Microscopic
Melting
Wind Control
Super Breath
Wallcrawling
Vision - Night
Vision - Infrared
Grim Reaping
Matter Absorption
The Force
Resurrection
Terrakinesis
Vision - Heat
Vitakinesis
Radar Sense
Qwardian Power Ring
Weather Control
Vision - X-Ray
Vision - Thermal
Web Creation
Reality Warping
Odin Force
Symbiote Costume
Speed Force
Phoenix Force
Molecular Dissipation
Vision - Cryo
Omnipresent
Omniscient

In [5]:
df.count()

Name                     534
Alignment                531
Intelligence_x           534
Strength                 534
Speed                    534
                        ...
Phoenix Force            534
Molecular Dissipation    534
Vision - Cryo            534
Omnipresent              534
Omniscient               534
Length: 182, dtype: int64

In [6]:
df.drop(['Intelligence_x', 'Strength', 'Speed', 'Durability_x', 'Power', 'Total', 'EyeColor', 'Race', 'HairColor', 'Publisher', 'Height', 'Weight', 'Agility'], axis=1, inplace=True)

In [7]:
df.head()

,Name,Alignment,Combat,Gender,SkinColor,Accelerated Healing,Lantern Power Ring,Dimensional Awareness,Cold Resistance,Stealth,...,Web Creation,Reality Warping,Odin Force,Symbiote Costume,Speed Force,Phoenix Force,Molecular Dissipation,Vision - Cryo,Omnipresent,Omniscient
0,A-Bomb,good,64,Male,-,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,Abe Sapien,good,85,Male,blue,True,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
2,Abin Sur,good,65,Male,red,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,Abomination,bad,95,Male,-,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,Abraxas,bad,56,Male,-,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False

In [8]:
small_df = df[["Gender", "Alignment", "Name"]]

In [9]:
small_df.head()

  Gender Alignment         Name
0   Male      good       A-Bomb
1   Male      good   Abe Sapien
2   Male      good     Abin Sur
3   Male       bad  Abomination
4   Male       bad      Abraxas

In [10]:
small_df.sort_values(by=["Gender"], inplace=False)
small_df

     Gender Alignment             Name
0      Male      good           A-Bomb
1      Male      good       Abe Sapien
2      Male      good         Abin Sur
3      Male       bad      Abomination
4      Male       bad          Abraxas
..      ...       ...              ...
529    Male      good     Yellowjacket
530  Female      good  Yellowjacket II
531    Male      good             Ymir
532  Female      good          Zatanna
533    Male       bad             Zoom

[534 rows x 3 columns]

In [11]:
small_df.sort_values(by=['Alignment'], inplace= True)
small_df

/Users/serendipitousfun/opt/anaconda3/lib/python3.9/site-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

    Gender Alignment        Name
533   Male       bad        Zoom
439   Male       bad    Sinestro
126   Male       bad     Carnage
433   Male       bad     Shocker
132   Male       bad   Chameleon
..     ...       ...         ...
310   Male   neutral     Man-Bat
491   Male   neutral        Toad
26    Male       NaN  Anti-Venom
88    Male       NaN   Blackwulf
495   Male       NaN   Trickster

[534 rows x 3 columns]

In [12]:
small_df.dropna()

    Gender Alignment        Name
533   Male       bad        Zoom
439   Male       bad    Sinestro
126   Male       bad     Carnage
433   Male       bad     Shocker
132   Male       bad   Chameleon
..     ...       ...         ...
76    Male   neutral     Bizarro
273   Male   neutral  Juggernaut
417   Male   neutral     Sandman
310   Male   neutral     Man-Bat
491   Male   neutral        Toad

[531 rows x 3 columns]

In [13]:
bad_male= small_df.groupby(["Alignment"]).get_group("bad")
bad_male

     Gender Alignment           Name
533    Male       bad           Zoom
439    Male       bad       Sinestro
126    Male       bad        Carnage
433    Male       bad        Shocker
132    Male       bad      Chameleon
..      ...       ...            ...
83   Female       bad    Black Mamba
337    Male       bad  Mister Freeze
474    Male       bad          Sylar
277    Male       bad       Kevin 11
77     Male       bad   Black Abbott

[151 rows x 3 columns]

In [16]:
bad_male= bad_male.groupby(["Gender"]).get_group("Male")
bad_male

    Gender Alignment           Name
533   Male       bad           Zoom
439   Male       bad       Sinestro
126   Male       bad        Carnage
433   Male       bad        Shocker
132   Male       bad      Chameleon
..     ...       ...            ...
72    Male       bad       Bird-Man
337   Male       bad  Mister Freeze
474   Male       bad          Sylar
277   Male       bad       Kevin 11
77    Male       bad   Black Abbott

[121 rows x 3 columns]

In [18]:
value = 1
bad_male['Value']= value
bad_male

    Gender Alignment           Name  Value
533   Male       bad           Zoom      1
439   Male       bad       Sinestro      1
126   Male       bad        Carnage      1
433   Male       bad        Shocker      1
132   Male       bad      Chameleon      1
..     ...       ...            ...    ...
72    Male       bad       Bird-Man      1
337   Male       bad  Mister Freeze      1
474   Male       bad          Sylar      1
277   Male       bad       Kevin 11      1
77    Male       bad   Black Abbott      1

[121 rows x 4 columns]

In [19]:
bmale = bad_male.to_json(orient="records")
parsed = json.loads(bmale)
json.dumps(parsed, indent=4)

'[\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Zoom",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Sinestro",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Carnage",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Shocker",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Chameleon",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Changeling",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Chromos",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Cogliostro",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Curse",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Cy-Gor",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Cyborg Superman",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Scorpion",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Scarecrow",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Solomon Grundy",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Iron Monger",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Blizzard",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Blizzard",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Blizzard II",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Blob",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Molten Man",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Bloodwraith",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Darkseid",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Morlun",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Brainiac",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Hydro-Man",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Moses Magnum",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Bullseye",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Hobgoblin",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Mister Sinister",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Magus",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Sabretooth",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Gog",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Red Skull",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Evilhawk",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Exodus",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Red Mist",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Fallen One II",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Razor-Fist II",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Ra\'s Al Ghul",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "General Zod",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Pyro",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Proto-Goblin",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Redeemer II",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Electro",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Redeemer III",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Green Goblin II",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Deadshot",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Green Goblin",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Demogoblin",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Destroyer",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Overtkill",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Doctor Doom",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Onslaught",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Doctor Doom II",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Penguin",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Riddler",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Rick Flag",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Doomsday",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Doppelganger",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Dormammu",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Rhino",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Doctor Octopus",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Blackwing",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Mister Mxyzptlk",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Lex Luthor",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Violator",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Leader",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Venom III",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Venom II",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Venom",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Vanisher",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Utgard-Loki",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Ultron",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Azazel",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Kraven the Hunter",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Blackout",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Bane",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Klaw",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Killer Croc",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Vulture",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Walrus",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Warp",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Apocalypse",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Magneto",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Abomination",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Abraxas",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Mandarin",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Mach-IV",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Air-Walker",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Luke Campbell",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Amazo",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Ammo",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Tinkerer",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Loki",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Lizard",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Weapon XI",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Match",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Annihilus",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Lightning Lord",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Anti-Monitor",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Anti-Spawn",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Lobo",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Mephisto",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Kraven II",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Billy Kincaid",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Junkpile",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Metallo",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Superboy-Prime",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Kang",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Thanos",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Black Adam",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Big Man",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Joker",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Swamp Thing",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Bird-Man II",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Tiger Shark",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Bird-Man",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Mister Freeze",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Sylar",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Kevin 11",\n        "Value": 1\n    },\n    {\n        "Gender": "Male",\n        "Alignment": "bad",\n        "Name": "Black Abbott",\n        "Value": 1\n    }\n]'

In [20]:
df.to_json(r'data_copy/bad_male.json')